SCRAPER_URLS = [
    # "https://cisomag.com/",
    # "https://www.techradar.com/in/news",
    # "https://cio.economictimes.indiatimes.com",
    # "https://www.thehindu.com/sci-tech/technology",
    # "https://www.techcircle.in",
    # "https://krebsonsecurity.com",
    # "https://thehackernews.com",
    # "https://www.securityweek.com",
    # "https://www.bleepingcomputer.com",
    # "https://www.darkreading.com",
    # "https://www.cyberscoop.com",
    # "https://threatpost.com",
    # "https://www.scmagazine.com",
    # "https://www.cisomag.com",
    # "https://www.techradar.com/in/news",
    # "https://cio.economictimes.indiatimes.com",
    "https://www.thehindu.com/sci-tech/technology",
    "https://www.techcircle.in",
    "https://www.indiatoday.in/technology",
    # "https://www.wired.com/category/security",
    # "https://techcrunch.com",
    # "https://mashable.com/tech",
    # "https://www.engadget.com/security",
    # "https://arstechnica.com/security",
    # "https://www.computerworld.com/category/security",
    # "https://www.zdnet.com/topic/security",
    # "https://www.infosecurity-magazine.com",
    # "https://www.troyhunt.com",
    # "https://www.schneier.com",
    # "https://isc.sans.edu",
    # "https://securityboulevard.com",
    "https://www.indiatoday.in/technology",
    "https://www.cert-in.org.in",
    "https://cybercrime.gov.in",
    "https://thehackernews.com",
    # "https://www.securityweek.com",
    # "https://www.bleepingcomputer.com/news/security/",
    # "https://www.cybersecuritynews.com/",
    # "https://www.darkreading.com",
    # "https://www.zerodium.com/",
    # "https://www.reddit.com/r/cybersecurity/",
    # "https://pastebin.com",
    # "https://threatpost.com",
    # "https://www.databreaches.net",
    "https://indianexpress.com/section/technology/",
    "https://economictimes.indiatimes.com/tech",
    "https://www.hindustantimes.com/tech/",
    # "https://www.zdnet.com/topic/security/",
    # "https://www.scmagazine.com/home/security-news/",
    "https://timesofindia.indiatimes.com/tech",
    "https://www.cvedetails.com/version-list/1224/19997/1/Google-Android.html",
    "https://cwe.mitre.org",
    "https://www.cvedetails.com/browse-by-date.php",
    "https://www.cvedetails.com/vulnerabilities-by-types.php"
]